//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.20 at 03:12:42 ip. EEST 
//


package dtBookTools;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for linegroup element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="linegroup">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://www.daisy.org/z3986/2005/dtbook/}hd"/>
 *           &lt;element ref="{http://www.daisy.org/z3986/2005/dtbook/}dateline"/>
 *           &lt;element ref="{http://www.daisy.org/z3986/2005/dtbook/}epigraph"/>
 *           &lt;element ref="{http://www.daisy.org/z3986/2005/dtbook/}byline"/>
 *           &lt;element ref="{http://www.daisy.org/z3986/2005/dtbook/}linegroup"/>
 *           &lt;element ref="{http://www.daisy.org/z3986/2005/dtbook/}line"/>
 *           &lt;element ref="{http://www.daisy.org/z3986/2005/dtbook/}pagenum"/>
 *           &lt;element ref="{http://www.daisy.org/z3986/2005/dtbook/}prodnote"/>
 *           &lt;element ref="{http://www.daisy.org/z3986/2005/dtbook/}noteref"/>
 *           &lt;element ref="{http://www.daisy.org/z3986/2005/dtbook/}annoref"/>
 *           &lt;element ref="{http://www.daisy.org/z3986/2005/dtbook/}note"/>
 *           &lt;element ref="{http://www.daisy.org/z3986/2005/dtbook/}annotation"/>
 *           &lt;element ref="{http://www.daisy.org/z3986/2005/dtbook/}p"/>
 *           &lt;element ref="{http://www.daisy.org/z3986/2005/dtbook/}blockquote"/>
 *           &lt;element ref="{http://www.daisy.org/z3986/2005/dtbook/}img"/>
 *           &lt;element ref="{http://www.daisy.org/z3986/2005/dtbook/}imggroup"/>
 *         &lt;/choice>
 *         &lt;attGroup ref="{http://www.daisy.org/z3986/2005/dtbook/}attlist.linegroup"/>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hdOrDatelineOrEpigraph"
})
@XmlRootElement(name = "linegroup")
public class Linegroup {

    @XmlElements({
        @XmlElement(name = "epigraph", namespace = "http://www.daisy.org/z3986/2005/dtbook/", required = true, type = Epigraph.class),
        @XmlElement(name = "annoref", namespace = "http://www.daisy.org/z3986/2005/dtbook/", required = true, type = Annoref.class),
        @XmlElement(name = "note", namespace = "http://www.daisy.org/z3986/2005/dtbook/", required = true, type = Note.class),
        @XmlElement(name = "p", namespace = "http://www.daisy.org/z3986/2005/dtbook/", required = true, type = P.class),
        @XmlElement(name = "annotation", namespace = "http://www.daisy.org/z3986/2005/dtbook/", required = true, type = Annotation.class),
        @XmlElement(name = "prodnote", namespace = "http://www.daisy.org/z3986/2005/dtbook/", required = true, type = Prodnote.class),
        @XmlElement(name = "noteref", namespace = "http://www.daisy.org/z3986/2005/dtbook/", required = true, type = Noteref.class),
        @XmlElement(name = "linegroup", namespace = "http://www.daisy.org/z3986/2005/dtbook/", required = true, type = Linegroup.class),
        @XmlElement(name = "dateline", namespace = "http://www.daisy.org/z3986/2005/dtbook/", required = true, type = Dateline.class),
        @XmlElement(name = "pagenum", namespace = "http://www.daisy.org/z3986/2005/dtbook/", required = true, type = Pagenum.class),
        @XmlElement(name = "blockquote", namespace = "http://www.daisy.org/z3986/2005/dtbook/", required = true, type = Blockquote.class),
        @XmlElement(name = "byline", namespace = "http://www.daisy.org/z3986/2005/dtbook/", required = true, type = Byline.class),
        @XmlElement(name = "line", namespace = "http://www.daisy.org/z3986/2005/dtbook/", required = true, type = Line.class),
        @XmlElement(name = "img", namespace = "http://www.daisy.org/z3986/2005/dtbook/", required = true, type = Img.class),
        @XmlElement(name = "hd", namespace = "http://www.daisy.org/z3986/2005/dtbook/", required = true, type = Hd.class),
        @XmlElement(name = "imggroup", namespace = "http://www.daisy.org/z3986/2005/dtbook/", required = true, type = Imggroup.class)
    })
    protected List<Object> hdOrDatelineOrEpigraph;
    @XmlAttribute
    protected String smilref;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dir;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lang;
    @XmlAttribute(name = "class")
    protected String clazz;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute
    protected String title;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String space;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String showin;

    /**
     * Gets the value of the hdOrDatelineOrEpigraph property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hdOrDatelineOrEpigraph property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHdOrDatelineOrEpigraph().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Epigraph }
     * {@link Annoref }
     * {@link Note }
     * {@link P }
     * {@link Annotation }
     * {@link Prodnote }
     * {@link Noteref }
     * {@link Linegroup }
     * {@link Dateline }
     * {@link Pagenum }
     * {@link Blockquote }
     * {@link Byline }
     * {@link Line }
     * {@link Img }
     * {@link Hd }
     * {@link Imggroup }
     * 
     * 
     */
    public List<Object> getHdOrDatelineOrEpigraph() {
        if (hdOrDatelineOrEpigraph == null) {
            hdOrDatelineOrEpigraph = new ArrayList<Object>();
        }
        return this.hdOrDatelineOrEpigraph;
    }

    /**
     * Gets the value of the smilref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmilref() {
        return smilref;
    }

    /**
     * Sets the value of the smilref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmilref(String value) {
        this.smilref = value;
    }

    /**
     * Gets the value of the dir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDir() {
        return dir;
    }

    /**
     * Sets the value of the dir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDir(String value) {
        this.dir = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }

    /**
     * Gets the value of the showin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowin() {
        return showin;
    }

    /**
     * Sets the value of the showin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowin(String value) {
        this.showin = value;
    }

}
