//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.20 at 03:12:42 ip. EEST 
//


package dtBookTools;

import java.util.ArrayList;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;group ref="{http://www.daisy.org/z3986/2005/dtbook/}block"/>
 *         &lt;group ref="{http://www.daisy.org/z3986/2005/dtbook/}inlineinblock"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://www.daisy.org/z3986/2005/dtbook/}attlist.note"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pOrListOrDl"
})
public class Note {

    @XmlElementRefs({
        @XmlElementRef(name = "samp", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Samp.class),
        @XmlElementRef(name = "div", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Div.class),
        @XmlElementRef(name = "cite", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Cite.class),
        @XmlElementRef(name = "pagenum", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Pagenum.class),
        @XmlElementRef(name = "line", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Line.class),
        @XmlElementRef(name = "kbd", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Kbd.class),
        @XmlElementRef(name = "imggroup", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = JAXBElement.class),
        @XmlElementRef(name = "list", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = dtBookTools.List.class),
        @XmlElementRef(name = "address", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Address.class),
        @XmlElementRef(name = "img", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = JAXBElement.class),
        @XmlElementRef(name = "byline", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Byline.class),
        @XmlElementRef(name = "linegroup", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Linegroup.class),
        @XmlElementRef(name = "poem", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Poem.class),
        @XmlElementRef(name = "a", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = A.class),
        @XmlElementRef(name = "dtbookblocknoimggroup", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = JAXBElement.class),
        @XmlElementRef(name = "dl", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Dl.class),
        @XmlElementRef(name = "table", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Table.class),
        @XmlElementRef(name = "epigraph", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Epigraph.class),
        @XmlElementRef(name = "dateline", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Dateline.class),
        @XmlElementRef(name = "p", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = P.class),
        @XmlElementRef(name = "blockquote", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Blockquote.class)
    })
    protected java.util.List<Object> pOrListOrDl;
    @XmlAttribute(name = "class")
    protected String clazz;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute
    protected String smilref;
    @XmlAttribute
    protected String title;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String space;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dir;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lang;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String showin;

    /**
     * Gets the value of the pOrListOrDl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pOrListOrDl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPOrListOrDl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Note }{@code >}
     * {@link Div }
     * {@link JAXBElement }{@code <}{@link Imggroup }{@code >}
     * {@link dtBookTools.List }
     * {@link JAXBElement }{@code <}{@link Prodnote }{@code >}
     * {@link Byline }
     * {@link A }
     * {@link Table }
     * {@link P }
     * {@link Blockquote }
     * {@link Samp }
     * {@link JAXBElement }{@code <}{@link Author }{@code >}
     * {@link Cite }
     * {@link JAXBElement }{@code <}{@link Sidebar }{@code >}
     * {@link Pagenum }
     * {@link Line }
     * {@link Kbd }
     * {@link Address }
     * {@link JAXBElement }{@code <}{@link Img }{@code >}
     * {@link Linegroup }
     * {@link Poem }
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link Dl }
     * {@link Epigraph }
     * {@link JAXBElement }{@code <}{@link Annotation }{@code >}
     * {@link Dateline }
     * 
     * 
     */
    public java.util.List<Object> getPOrListOrDl() {
        if (pOrListOrDl == null) {
            pOrListOrDl = new ArrayList<Object>();
        }
        return this.pOrListOrDl;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the smilref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmilref() {
        return smilref;
    }

    /**
     * Sets the value of the smilref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmilref(String value) {
        this.smilref = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }

    /**
     * Gets the value of the dir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDir() {
        return dir;
    }

    /**
     * Sets the value of the dir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDir(String value) {
        this.dir = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the showin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowin() {
        return showin;
    }

    /**
     * Sets the value of the showin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowin(String value) {
        this.showin = value;
    }

}
