//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.20 at 03:12:42 ip. EEST 
//


package dtBookTools;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dtBookTools package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Imggroup_QNAME = new QName("http://www.daisy.org/z3986/2005/dtbook/", "imggroup");
    private final static QName _Span_QNAME = new QName("http://www.daisy.org/z3986/2005/dtbook/", "span");
    private final static QName _Q_QNAME = new QName("http://www.daisy.org/z3986/2005/dtbook/", "q");
    private final static QName _Br_QNAME = new QName("http://www.daisy.org/z3986/2005/dtbook/", "br");
    private final static QName _Sidebar_QNAME = new QName("http://www.daisy.org/z3986/2005/dtbook/", "sidebar");
    private final static QName _Meta_QNAME = new QName("http://www.daisy.org/z3986/2005/dtbook/", "meta");
    private final static QName _Dtbookblocknoimggroup_QNAME = new QName("http://www.daisy.org/z3986/2005/dtbook/", "dtbookblocknoimggroup");
    private final static QName _Link_QNAME = new QName("http://www.daisy.org/z3986/2005/dtbook/", "link");
    private final static QName _Sup_QNAME = new QName("http://www.daisy.org/z3986/2005/dtbook/", "sup");
    private final static QName _Bdo_QNAME = new QName("http://www.daisy.org/z3986/2005/dtbook/", "bdo");
    private final static QName _Specialnoa_QNAME = new QName("http://www.daisy.org/z3986/2005/dtbook/", "specialnoa");
    private final static QName _Img_QNAME = new QName("http://www.daisy.org/z3986/2005/dtbook/", "img");
    private final static QName _Note_QNAME = new QName("http://www.daisy.org/z3986/2005/dtbook/", "note");
    private final static QName _Sub_QNAME = new QName("http://www.daisy.org/z3986/2005/dtbook/", "sub");
    private final static QName _Prodnote_QNAME = new QName("http://www.daisy.org/z3986/2005/dtbook/", "prodnote");
    private final static QName _Annotation_QNAME = new QName("http://www.daisy.org/z3986/2005/dtbook/", "annotation");
    private final static QName _Author_QNAME = new QName("http://www.daisy.org/z3986/2005/dtbook/", "author");
    private final static QName _Headmisc_QNAME = new QName("http://www.daisy.org/z3986/2005/dtbook/", "headmisc");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dtBookTools
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Covertitle }
     * 
     */
    public Covertitle createCovertitle() {
        return new Covertitle();
    }

    /**
     * Create an instance of {@link Div }
     * 
     */
    public Div createDiv() {
        return new Div();
    }

    /**
     * Create an instance of {@link Level3 }
     * 
     */
    public Level3 createLevel3() {
        return new Level3();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link Dtbookcontent }
     * 
     */
    public Dtbookcontent createDtbookcontent() {
        return new Dtbookcontent();
    }

    /**
     * Create an instance of {@link Lic }
     * 
     */
    public Lic createLic() {
        return new Lic();
    }

    /**
     * Create an instance of {@link Dtbook }
     * 
     */
    public Dtbook createDtbook() {
        return new Dtbook();
    }

    /**
     * Create an instance of {@link Acronym }
     * 
     */
    public Acronym createAcronym() {
        return new Acronym();
    }

    /**
     * Create an instance of {@link H5 }
     * 
     */
    public H5 createH5() {
        return new H5();
    }

    /**
     * Create an instance of {@link Td }
     * 
     */
    public Td createTd() {
        return new Td();
    }

    /**
     * Create an instance of {@link A }
     * 
     */
    public A createA() {
        return new A();
    }

    /**
     * Create an instance of {@link Level6 }
     * 
     */
    public Level6 createLevel6() {
        return new Level6();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link Level5 }
     * 
     */
    public Level5 createLevel5() {
        return new Level5();
    }

    /**
     * Create an instance of {@link P }
     * 
     */
    public P createP() {
        return new P();
    }

    /**
     * Create an instance of {@link Sup }
     * 
     */
    public Sup createSup() {
        return new Sup();
    }

    /**
     * Create an instance of {@link Caption }
     * 
     */
    public Caption createCaption() {
        return new Caption();
    }

    /**
     * Create an instance of {@link Strong }
     * 
     */
    public Strong createStrong() {
        return new Strong();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link Imggroup }
     * 
     */
    public Imggroup createImggroup() {
        return new Imggroup();
    }

    /**
     * Create an instance of {@link Sub }
     * 
     */
    public Sub createSub() {
        return new Sub();
    }

    /**
     * Create an instance of {@link Cite }
     * 
     */
    public Cite createCite() {
        return new Cite();
    }

    /**
     * Create an instance of {@link Pagenum }
     * 
     */
    public Pagenum createPagenum() {
        return new Pagenum();
    }

    /**
     * Create an instance of {@link Span }
     * 
     */
    public Span createSpan() {
        return new Span();
    }

    /**
     * Create an instance of {@link Head }
     * 
     */
    public Head createHead() {
        return new Head();
    }

    /**
     * Create an instance of {@link Line }
     * 
     */
    public Line createLine() {
        return new Line();
    }

    /**
     * Create an instance of {@link Kbd }
     * 
     */
    public Kbd createKbd() {
        return new Kbd();
    }

    /**
     * Create an instance of {@link Book }
     * 
     */
    public Book createBook() {
        return new Book();
    }

    /**
     * Create an instance of {@link H3 }
     * 
     */
    public H3 createH3() {
        return new H3();
    }

    /**
     * Create an instance of {@link Hd }
     * 
     */
    public Hd createHd() {
        return new Hd();
    }

    /**
     * Create an instance of {@link H2 }
     * 
     */
    public H2 createH2() {
        return new H2();
    }

    /**
     * Create an instance of {@link Bodymatter }
     * 
     */
    public Bodymatter createBodymatter() {
        return new Bodymatter();
    }

    /**
     * Create an instance of {@link Dt }
     * 
     */
    public Dt createDt() {
        return new Dt();
    }

    /**
     * Create an instance of {@link Level2 }
     * 
     */
    public Level2 createLevel2() {
        return new Level2();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Frontmatter }
     * 
     */
    public Frontmatter createFrontmatter() {
        return new Frontmatter();
    }

    /**
     * Create an instance of {@link Sidebar }
     * 
     */
    public Sidebar createSidebar() {
        return new Sidebar();
    }

    /**
     * Create an instance of {@link Col }
     * 
     */
    public Col createCol() {
        return new Col();
    }

    /**
     * Create an instance of {@link Doctitle }
     * 
     */
    public Doctitle createDoctitle() {
        return new Doctitle();
    }

    /**
     * Create an instance of {@link Bdo }
     * 
     */
    public Bdo createBdo() {
        return new Bdo();
    }

    /**
     * Create an instance of {@link Code }
     * 
     */
    public Code createCode() {
        return new Code();
    }

    /**
     * Create an instance of {@link Abbr }
     * 
     */
    public Abbr createAbbr() {
        return new Abbr();
    }

    /**
     * Create an instance of {@link Level }
     * 
     */
    public Level createLevel() {
        return new Level();
    }

    /**
     * Create an instance of {@link Tfoot }
     * 
     */
    public Tfoot createTfoot() {
        return new Tfoot();
    }

    /**
     * Create an instance of {@link Noteref }
     * 
     */
    public Noteref createNoteref() {
        return new Noteref();
    }

    /**
     * Create an instance of {@link Tr }
     * 
     */
    public Tr createTr() {
        return new Tr();
    }

    /**
     * Create an instance of {@link List }
     * 
     */
    public List createList() {
        return new List();
    }

    /**
     * Create an instance of {@link Byline }
     * 
     */
    public Byline createByline() {
        return new Byline();
    }

    /**
     * Create an instance of {@link Br }
     * 
     */
    public Br createBr() {
        return new Br();
    }

    /**
     * Create an instance of {@link H6 }
     * 
     */
    public H6 createH6() {
        return new H6();
    }

    /**
     * Create an instance of {@link Level1 }
     * 
     */
    public Level1 createLevel1() {
        return new Level1();
    }

    /**
     * Create an instance of {@link H4 }
     * 
     */
    public H4 createH4() {
        return new H4();
    }

    /**
     * Create an instance of {@link Rearmatter }
     * 
     */
    public Rearmatter createRearmatter() {
        return new Rearmatter();
    }

    /**
     * Create an instance of {@link Em }
     * 
     */
    public Em createEm() {
        return new Em();
    }

    /**
     * Create an instance of {@link Dd }
     * 
     */
    public Dd createDd() {
        return new Dd();
    }

    /**
     * Create an instance of {@link Docauthor }
     * 
     */
    public Docauthor createDocauthor() {
        return new Docauthor();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link Meta }
     * 
     */
    public Meta createMeta() {
        return new Meta();
    }

    /**
     * Create an instance of {@link Prodnote }
     * 
     */
    public Prodnote createProdnote() {
        return new Prodnote();
    }

    /**
     * Create an instance of {@link Sent }
     * 
     */
    public Sent createSent() {
        return new Sent();
    }

    /**
     * Create an instance of {@link Blockquote }
     * 
     */
    public Blockquote createBlockquote() {
        return new Blockquote();
    }

    /**
     * Create an instance of {@link Dfn }
     * 
     */
    public Dfn createDfn() {
        return new Dfn();
    }

    /**
     * Create an instance of {@link Samp }
     * 
     */
    public Samp createSamp() {
        return new Samp();
    }

    /**
     * Create an instance of {@link Th }
     * 
     */
    public Th createTh() {
        return new Th();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Annoref }
     * 
     */
    public Annoref createAnnoref() {
        return new Annoref();
    }

    /**
     * Create an instance of {@link H1 }
     * 
     */
    public H1 createH1() {
        return new H1();
    }

    /**
     * Create an instance of {@link W }
     * 
     */
    public W createW() {
        return new W();
    }

    /**
     * Create an instance of {@link Img }
     * 
     */
    public Img createImg() {
        return new Img();
    }

    /**
     * Create an instance of {@link Thead }
     * 
     */
    public Thead createThead() {
        return new Thead();
    }

    /**
     * Create an instance of {@link Linegroup }
     * 
     */
    public Linegroup createLinegroup() {
        return new Linegroup();
    }

    /**
     * Create an instance of {@link Annotation }
     * 
     */
    public Annotation createAnnotation() {
        return new Annotation();
    }

    /**
     * Create an instance of {@link Poem }
     * 
     */
    public Poem createPoem() {
        return new Poem();
    }

    /**
     * Create an instance of {@link Dl }
     * 
     */
    public Dl createDl() {
        return new Dl();
    }

    /**
     * Create an instance of {@link Q }
     * 
     */
    public Q createQ() {
        return new Q();
    }

    /**
     * Create an instance of {@link Level4 }
     * 
     */
    public Level4 createLevel4() {
        return new Level4();
    }

    /**
     * Create an instance of {@link Epigraph }
     * 
     */
    public Epigraph createEpigraph() {
        return new Epigraph();
    }

    /**
     * Create an instance of {@link Dateline }
     * 
     */
    public Dateline createDateline() {
        return new Dateline();
    }

    /**
     * Create an instance of {@link Colgroup }
     * 
     */
    public Colgroup createColgroup() {
        return new Colgroup();
    }

    /**
     * Create an instance of {@link Bridgehead }
     * 
     */
    public Bridgehead createBridgehead() {
        return new Bridgehead();
    }

    /**
     * Create an instance of {@link Linenum }
     * 
     */
    public Linenum createLinenum() {
        return new Linenum();
    }

    /**
     * Create an instance of {@link Tbody }
     * 
     */
    public Tbody createTbody() {
        return new Tbody();
    }

    /**
     * Create an instance of {@link Li }
     * 
     */
    public Li createLi() {
        return new Li();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Imggroup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.daisy.org/z3986/2005/dtbook/", name = "imggroup", substitutionHeadNamespace = "http://www.daisy.org/z3986/2005/dtbook/", substitutionHeadName = "specialnoa")
    public JAXBElement<Imggroup> createImggroup(Imggroup value) {
        return new JAXBElement<Imggroup>(_Imggroup_QNAME, Imggroup.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Span }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.daisy.org/z3986/2005/dtbook/", name = "span", substitutionHeadNamespace = "http://www.daisy.org/z3986/2005/dtbook/", substitutionHeadName = "specialnoa")
    public JAXBElement<Span> createSpan(Span value) {
        return new JAXBElement<Span>(_Span_QNAME, Span.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Q }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.daisy.org/z3986/2005/dtbook/", name = "q", substitutionHeadNamespace = "http://www.daisy.org/z3986/2005/dtbook/", substitutionHeadName = "specialnoa")
    public JAXBElement<Q> createQ(Q value) {
        return new JAXBElement<Q>(_Q_QNAME, Q.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Br }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.daisy.org/z3986/2005/dtbook/", name = "br", substitutionHeadNamespace = "http://www.daisy.org/z3986/2005/dtbook/", substitutionHeadName = "specialnoa")
    public JAXBElement<Br> createBr(Br value) {
        return new JAXBElement<Br>(_Br_QNAME, Br.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sidebar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.daisy.org/z3986/2005/dtbook/", name = "sidebar", substitutionHeadNamespace = "http://www.daisy.org/z3986/2005/dtbook/", substitutionHeadName = "dtbookblocknoimggroup")
    public JAXBElement<Sidebar> createSidebar(Sidebar value) {
        return new JAXBElement<Sidebar>(_Sidebar_QNAME, Sidebar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Meta }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.daisy.org/z3986/2005/dtbook/", name = "meta", substitutionHeadNamespace = "http://www.daisy.org/z3986/2005/dtbook/", substitutionHeadName = "headmisc")
    public JAXBElement<Meta> createMeta(Meta value) {
        return new JAXBElement<Meta>(_Meta_QNAME, Meta.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.daisy.org/z3986/2005/dtbook/", name = "dtbookblocknoimggroup")
    public JAXBElement<Object> createDtbookblocknoimggroup(Object value) {
        return new JAXBElement<Object>(_Dtbookblocknoimggroup_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Link }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.daisy.org/z3986/2005/dtbook/", name = "link", substitutionHeadNamespace = "http://www.daisy.org/z3986/2005/dtbook/", substitutionHeadName = "headmisc")
    public JAXBElement<Link> createLink(Link value) {
        return new JAXBElement<Link>(_Link_QNAME, Link.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.daisy.org/z3986/2005/dtbook/", name = "sup", substitutionHeadNamespace = "http://www.daisy.org/z3986/2005/dtbook/", substitutionHeadName = "specialnoa")
    public JAXBElement<Sup> createSup(Sup value) {
        return new JAXBElement<Sup>(_Sup_QNAME, Sup.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Bdo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.daisy.org/z3986/2005/dtbook/", name = "bdo", substitutionHeadNamespace = "http://www.daisy.org/z3986/2005/dtbook/", substitutionHeadName = "specialnoa")
    public JAXBElement<Bdo> createBdo(Bdo value) {
        return new JAXBElement<Bdo>(_Bdo_QNAME, Bdo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.daisy.org/z3986/2005/dtbook/", name = "specialnoa")
    public JAXBElement<Object> createSpecialnoa(Object value) {
        return new JAXBElement<Object>(_Specialnoa_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Img }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.daisy.org/z3986/2005/dtbook/", name = "img", substitutionHeadNamespace = "http://www.daisy.org/z3986/2005/dtbook/", substitutionHeadName = "specialnoa")
    public JAXBElement<Img> createImg(Img value) {
        return new JAXBElement<Img>(_Img_QNAME, Img.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Note }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.daisy.org/z3986/2005/dtbook/", name = "note", substitutionHeadNamespace = "http://www.daisy.org/z3986/2005/dtbook/", substitutionHeadName = "dtbookblocknoimggroup")
    public JAXBElement<Note> createNote(Note value) {
        return new JAXBElement<Note>(_Note_QNAME, Note.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sub }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.daisy.org/z3986/2005/dtbook/", name = "sub", substitutionHeadNamespace = "http://www.daisy.org/z3986/2005/dtbook/", substitutionHeadName = "specialnoa")
    public JAXBElement<Sub> createSub(Sub value) {
        return new JAXBElement<Sub>(_Sub_QNAME, Sub.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prodnote }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.daisy.org/z3986/2005/dtbook/", name = "prodnote", substitutionHeadNamespace = "http://www.daisy.org/z3986/2005/dtbook/", substitutionHeadName = "dtbookblocknoimggroup")
    public JAXBElement<Prodnote> createProdnote(Prodnote value) {
        return new JAXBElement<Prodnote>(_Prodnote_QNAME, Prodnote.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Annotation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.daisy.org/z3986/2005/dtbook/", name = "annotation", substitutionHeadNamespace = "http://www.daisy.org/z3986/2005/dtbook/", substitutionHeadName = "dtbookblocknoimggroup")
    public JAXBElement<Annotation> createAnnotation(Annotation value) {
        return new JAXBElement<Annotation>(_Annotation_QNAME, Annotation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Author }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.daisy.org/z3986/2005/dtbook/", name = "author", substitutionHeadNamespace = "http://www.daisy.org/z3986/2005/dtbook/", substitutionHeadName = "dtbookblocknoimggroup")
    public JAXBElement<Author> createAuthor(Author value) {
        return new JAXBElement<Author>(_Author_QNAME, Author.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.daisy.org/z3986/2005/dtbook/", name = "headmisc")
    public JAXBElement<Object> createHeadmisc(Object value) {
        return new JAXBElement<Object>(_Headmisc_QNAME, Object.class, null, value);
    }

}
