//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 12:20:44 ip. EEST 
//


package dtBookTools.binded;

import java.util.ArrayList;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for level4 element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="level4">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://www.daisy.org/z3986/2005/dtbook/}h4"/>
 *             &lt;choice maxOccurs="unbounded">
 *               &lt;group ref="{http://www.daisy.org/z3986/2005/dtbook/}docblockorinline"/>
 *               &lt;element ref="{http://www.daisy.org/z3986/2005/dtbook/}level5"/>
 *             &lt;/choice>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;choice maxOccurs="unbounded">
 *               &lt;group ref="{http://www.daisy.org/z3986/2005/dtbook/}docblockorinline"/>
 *               &lt;element ref="{http://www.daisy.org/z3986/2005/dtbook/}level5"/>
 *             &lt;/choice>
 *             &lt;sequence minOccurs="0">
 *               &lt;element ref="{http://www.daisy.org/z3986/2005/dtbook/}h4"/>
 *               &lt;choice maxOccurs="unbounded">
 *                 &lt;group ref="{http://www.daisy.org/z3986/2005/dtbook/}docblockorinline"/>
 *                 &lt;element ref="{http://www.daisy.org/z3986/2005/dtbook/}level5"/>
 *               &lt;/choice>
 *             &lt;/sequence>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;attGroup ref="{http://www.daisy.org/z3986/2005/dtbook/}attlist.level4"/>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "level4")
public class Level4 {

    @XmlElementRefs({
        @XmlElementRef(name = "line", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Line.class),
        @XmlElementRef(name = "poem", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Poem.class),
        @XmlElementRef(name = "linegroup", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Linegroup.class),
        @XmlElementRef(name = "list", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = dtBookTools.binded.List.class),
        @XmlElementRef(name = "samp", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Samp.class),
        @XmlElementRef(name = "pagenum", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Pagenum.class),
        @XmlElementRef(name = "table", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Table.class),
        @XmlElementRef(name = "a", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = A.class),
        @XmlElementRef(name = "bridgehead", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Bridgehead.class),
        @XmlElementRef(name = "epigraph", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Epigraph.class),
        @XmlElementRef(name = "docauthor", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Docauthor.class),
        @XmlElementRef(name = "covertitle", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Covertitle.class),
        @XmlElementRef(name = "p", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = P.class),
        @XmlElementRef(name = "dateline", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Dateline.class),
        @XmlElementRef(name = "img", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = JAXBElement.class),
        @XmlElementRef(name = "dtbookblocknoimggroup", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = JAXBElement.class),
        @XmlElementRef(name = "cite", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Cite.class),
        @XmlElementRef(name = "div", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Div.class),
        @XmlElementRef(name = "h4", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = H4 .class),
        @XmlElementRef(name = "address", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Address.class),
        @XmlElementRef(name = "blockquote", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Blockquote.class),
        @XmlElementRef(name = "doctitle", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Doctitle.class),
        @XmlElementRef(name = "kbd", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Kbd.class),
        @XmlElementRef(name = "level5", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Level5 .class),
        @XmlElementRef(name = "imggroup", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = JAXBElement.class),
        @XmlElementRef(name = "byline", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Byline.class),
        @XmlElementRef(name = "dl", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Dl.class)
    })
    protected java.util.List<Object> content;
    @XmlAttribute
    protected String smilref;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String showin;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dir;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lang;
    @XmlAttribute(name = "class")
    protected String clazz;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute
    protected String title;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String space;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "H4" is used by two different parts of a schema. See: 
     * line 1635 of file:/C:/Users/jukkae/git/dtBookTools/DTBookTools/lib/dtbook-2005-3.xsd
     * line 1623 of file:/C:/Users/jukkae/git/dtBookTools/DTBookTools/lib/dtbook-2005-3.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Line }
     * {@link JAXBElement }{@code <}{@link Annotation }{@code >}
     * {@link Poem }
     * {@link Linegroup }
     * {@link dtBookTools.binded.List }
     * {@link Samp }
     * {@link Pagenum }
     * {@link Table }
     * {@link A }
     * {@link Bridgehead }
     * {@link Epigraph }
     * {@link Docauthor }
     * {@link Covertitle }
     * {@link JAXBElement }{@code <}{@link Prodnote }{@code >}
     * {@link P }
     * {@link Dateline }
     * {@link JAXBElement }{@code <}{@link Img }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Note }{@code >}
     * {@link Cite }
     * {@link Div }
     * {@link H4 }
     * {@link Address }
     * {@link Blockquote }
     * {@link JAXBElement }{@code <}{@link Author }{@code >}
     * {@link Doctitle }
     * {@link Kbd }
     * {@link Level5 }
     * {@link JAXBElement }{@code <}{@link Imggroup }{@code >}
     * {@link JAXBElement }{@code <}{@link Sidebar }{@code >}
     * {@link Byline }
     * {@link Dl }
     * 
     * 
     */
    public java.util.List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the smilref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmilref() {
        return smilref;
    }

    /**
     * Sets the value of the smilref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmilref(String value) {
        this.smilref = value;
    }

    /**
     * Gets the value of the showin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowin() {
        return showin;
    }

    /**
     * Sets the value of the showin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowin(String value) {
        this.showin = value;
    }

    /**
     * Gets the value of the dir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDir() {
        return dir;
    }

    /**
     * Sets the value of the dir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDir(String value) {
        this.dir = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }

}
