//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 12:20:44 ip. EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.daisy.org/z3986/2005/dtbook/")
package dtBookTools.binded;
