//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 12:20:44 ip. EEST 
//


package dtBookTools.binded;

import java.util.ArrayList;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for td element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="td">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;group ref="{http://www.daisy.org/z3986/2005/dtbook/}flownopagenum" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;attGroup ref="{http://www.daisy.org/z3986/2005/dtbook/}attlist.td"/>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "td")
public class Td {

    @XmlElementRefs({
        @XmlElementRef(name = "line", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Line.class),
        @XmlElementRef(name = "noteref", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Noteref.class),
        @XmlElementRef(name = "abbr", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Abbr.class),
        @XmlElementRef(name = "poem", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Poem.class),
        @XmlElementRef(name = "linegroup", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Linegroup.class),
        @XmlElementRef(name = "strong", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Strong.class),
        @XmlElementRef(name = "samp", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Samp.class),
        @XmlElementRef(name = "list", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = dtBookTools.binded.List.class),
        @XmlElementRef(name = "sub", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = JAXBElement.class),
        @XmlElementRef(name = "sent", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Sent.class),
        @XmlElementRef(name = "annoref", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Annoref.class),
        @XmlElementRef(name = "table", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Table.class),
        @XmlElementRef(name = "a", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = A.class),
        @XmlElementRef(name = "epigraph", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Epigraph.class),
        @XmlElementRef(name = "q", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = JAXBElement.class),
        @XmlElementRef(name = "p", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = P.class),
        @XmlElementRef(name = "dateline", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Dateline.class),
        @XmlElementRef(name = "img", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = JAXBElement.class),
        @XmlElementRef(name = "dtbookblocknoimggroup", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = JAXBElement.class),
        @XmlElementRef(name = "span", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = JAXBElement.class),
        @XmlElementRef(name = "bdo", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = JAXBElement.class),
        @XmlElementRef(name = "br", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = JAXBElement.class),
        @XmlElementRef(name = "div", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Div.class),
        @XmlElementRef(name = "cite", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Cite.class),
        @XmlElementRef(name = "address", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Address.class),
        @XmlElementRef(name = "code", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Code.class),
        @XmlElementRef(name = "dfn", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Dfn.class),
        @XmlElementRef(name = "blockquote", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Blockquote.class),
        @XmlElementRef(name = "w", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = W.class),
        @XmlElementRef(name = "kbd", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Kbd.class),
        @XmlElementRef(name = "em", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Em.class),
        @XmlElementRef(name = "imggroup", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = JAXBElement.class),
        @XmlElementRef(name = "byline", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Byline.class),
        @XmlElementRef(name = "acronym", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Acronym.class),
        @XmlElementRef(name = "sup", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = JAXBElement.class),
        @XmlElementRef(name = "dl", namespace = "http://www.daisy.org/z3986/2005/dtbook/", type = Dl.class)
    })
    @XmlMixed
    protected java.util.List<Object> content;
    @XmlAttribute
    protected String abbr;
    @XmlAttribute
    protected String axis;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String colspan;
    @XmlAttribute
    @XmlIDREF
    protected java.util.List<Object> headers;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rowspan;
    @XmlAttribute
    protected Scope scope;
    @XmlAttribute
    protected String smilref;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String showin;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dir;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lang;
    @XmlAttribute(name = "class")
    protected String clazz;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute
    protected String title;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String space;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String align;
    @XmlAttribute(name = "char")
    protected String _char;
    @XmlAttribute
    protected String charoff;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String valign;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Line }
     * {@link Noteref }
     * {@link JAXBElement }{@code <}{@link Annotation }{@code >}
     * {@link Abbr }
     * {@link Poem }
     * {@link Linegroup }
     * {@link Strong }
     * {@link Samp }
     * {@link dtBookTools.binded.List }
     * {@link JAXBElement }{@code <}{@link Sub }{@code >}
     * {@link Sent }
     * {@link Annoref }
     * {@link Table }
     * {@link A }
     * {@link Epigraph }
     * {@link JAXBElement }{@code <}{@link Q }{@code >}
     * {@link JAXBElement }{@code <}{@link Prodnote }{@code >}
     * {@link P }
     * {@link Dateline }
     * {@link JAXBElement }{@code <}{@link Img }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Note }{@code >}
     * {@link JAXBElement }{@code <}{@link Span }{@code >}
     * {@link JAXBElement }{@code <}{@link Bdo }{@code >}
     * {@link JAXBElement }{@code <}{@link Br }{@code >}
     * {@link Div }
     * {@link Cite }
     * {@link Address }
     * {@link Code }
     * {@link Dfn }
     * {@link Blockquote }
     * {@link JAXBElement }{@code <}{@link Author }{@code >}
     * {@link W }
     * {@link Kbd }
     * {@link Em }
     * {@link JAXBElement }{@code <}{@link Imggroup }{@code >}
     * {@link JAXBElement }{@code <}{@link Sidebar }{@code >}
     * {@link Byline }
     * {@link Acronym }
     * {@link JAXBElement }{@code <}{@link Sup }{@code >}
     * {@link Dl }
     * {@link String }
     * 
     * 
     */
    public java.util.List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the abbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbbr() {
        return abbr;
    }

    /**
     * Sets the value of the abbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbbr(String value) {
        this.abbr = value;
    }

    /**
     * Gets the value of the axis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAxis() {
        return axis;
    }

    /**
     * Sets the value of the axis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAxis(String value) {
        this.axis = value;
    }

    /**
     * Gets the value of the colspan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColspan() {
        if (colspan == null) {
            return "1";
        } else {
            return colspan;
        }
    }

    /**
     * Sets the value of the colspan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColspan(String value) {
        this.colspan = value;
    }

    /**
     * Gets the value of the headers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the headers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHeaders().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public java.util.List<Object> getHeaders() {
        if (headers == null) {
            headers = new ArrayList<Object>();
        }
        return this.headers;
    }

    /**
     * Gets the value of the rowspan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRowspan() {
        if (rowspan == null) {
            return "1";
        } else {
            return rowspan;
        }
    }

    /**
     * Sets the value of the rowspan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRowspan(String value) {
        this.rowspan = value;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link Scope }
     *     
     */
    public Scope getScope() {
        return scope;
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link Scope }
     *     
     */
    public void setScope(Scope value) {
        this.scope = value;
    }

    /**
     * Gets the value of the smilref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmilref() {
        return smilref;
    }

    /**
     * Sets the value of the smilref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmilref(String value) {
        this.smilref = value;
    }

    /**
     * Gets the value of the showin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowin() {
        return showin;
    }

    /**
     * Sets the value of the showin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowin(String value) {
        this.showin = value;
    }

    /**
     * Gets the value of the dir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDir() {
        return dir;
    }

    /**
     * Sets the value of the dir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDir(String value) {
        this.dir = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }

    /**
     * Gets the value of the align property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlign() {
        return align;
    }

    /**
     * Sets the value of the align property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlign(String value) {
        this.align = value;
    }

    /**
     * Gets the value of the char property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChar() {
        return _char;
    }

    /**
     * Sets the value of the char property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChar(String value) {
        this._char = value;
    }

    /**
     * Gets the value of the charoff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCharoff() {
        return charoff;
    }

    /**
     * Sets the value of the charoff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCharoff(String value) {
        this.charoff = value;
    }

    /**
     * Gets the value of the valign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValign() {
        return valign;
    }

    /**
     * Sets the value of the valign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValign(String value) {
        this.valign = value;
    }

}
